### ISSUE TITLE
Hero HP values moved up 1 pixel in nightly?

### ISSUE THREAD

**Issue by Feenick** [ohrrpgce/ohrrpgce#1237] opened 2022-04-14 19:54 UTC
Old:
![falsesky0097](https://user-images.githubusercontent.com/45484204/163465887-12545442-2d92-4e73-b4a4-2c2794889a61.png)
New:
![falsesky0110](https://user-images.githubusercontent.com/45484204/163465806-84ff4536-4bbc-408b-b06e-81fb0f23f8de.png)

**Comment by rversteegen** [comment] 2022-04-15 00:43
It used to be the case that if you enabled MP meters the HP values would shift up by one pixel; I did that to make it easier to see the MP meters. Recently James rewrote the battle UI using slices. He wrote (discussion of r12830):

> If you turn bat.test_future to toggle mode, you'll easily see that this is not a pixel perfect match for the old code.
> 
> Specifically, rather than shifting the HP text up one pixel in response to MP meter visibility, I just leave it up one pixel in the slice based ui.
> 
> The one pixel shift up is such a weird specific hack that I haven't thought of a good way to reproduce it generically with slices

I have a draft of a reply I never sent:

> One way to reproduce the one pixel shift would be to parent the HP text and MP meter to a layout slice which stacks vertically from the bottom, with a negative child padding so that the presence of the MP meter shifts the text up by a pixel.

(Currently, the HP and MP meters, HP text and icon grid area are all children of the same container.)
This is a pretty ugly solution, and when it becomes customisable people will probably be confused by the layout slice, which becomes unnecessary when you can customise slice positions. But it's definitely preferable to do slice positioning entirely using slices rather than to hardcode anything.

**Comment by rversteegen** [comment] 2022-04-23 05:07
James, any thoughts on my proposed solution?

**Comment by bob-the-hamster** [comment] 2022-04-23 13:19
Oh, using the layout slice? Yes, I am fine with that. I read it, but it
just got burried in my inbox and I forgot to reply. It's a good idea.

I know we still need to add layout slice support to the slice editor, don't
we?

Although we'll eventually enable full customization of these slices, I also
want to have a bunch of pre-defined slice collections for battle ui that
people can just pick from. The current one would be "Classic" -- so since
your proposed fix makes it better match the actual old non-slice layout,
yes we should do it.

**Comment by rversteegen** [comment] 2022-04-24 00:37
OK, I'll do this.

The slice editor fully supports layout slices, but only shows the option to create them in privileged mode. Of course you can edit existing ones.

**Comment by bob-the-hamster** [comment] 2022-04-24 01:26
Oh, cool, I guess I just didn't test in privileged mode.

Is there a reason they still need to stay in privilege mode?

**Comment by rversteegen** [comment] 2022-04-24 02:57
It's just because of the refreshing layout slice problem where you need to double-refresh, or worse when they're nested. But the main problem might actually be with Cover Children rather than layout slices. And AFAIK there is no bug specifically with layout slices, the problem is with Slice.ChildrenRefresh (used only by layout slices).
I can't actually see how the delayed refresh bug is a backcompat problem, so there's no reason not to just expose layout slices despite the bug. I'll look into it and see whether Cover Children is also ready for ichorescent.

**Comment by rversteegen** [comment] 2022-12-07 02:12
Fixed in r13151 (3a36b2d9) using a Layout slice as I suggested. Honestly it was pretty difficult to set up the Layout slice right to replicate the old behaviour, it's a messy solution.

Shifting the text up a pixel was and is done independently for each hero. If a hero doesn't have MP the text isn't moved up, causing wonky looking spacing, not ideal. Even assuming consistent spacing there's only one pixel between lines of HP text so only one pixel of the MP meter will be visible (except for the last hero) regardless of where it's positioned anyway.

I thought of a far simpler alternative. Don't move the text up, instead draw the MP bar 1px lower (this will put it halfway between two heroes' stats) and make the HP bar 1px thinner so that it doesn't overdraw the MP meter of the hero above. I think moving the MP bar is no problem, but there are games with backdrops for the exact size/position of the HP bars? Probably fine

Alternatively, if we had draw ordering we could make all the MP meters draw over all the HP meters without modifying the HP bars. I really want to implement draw ordering, it would be a fantastically useful feature, and fun to implement, just need to decide exactly how it works.

Offtopic stuff:

I decided we should expose Layout slices, I only want to change how children of Layout slices set to Fill Parent act, to fill the remaining space instead. But I think Cover Children needs to be rewritten quite differently before it's exposed, it's far too buggy.

**Closed as completed by rversteegen** 2022-12-07 02:12 UTC
Labels: release-blocker, battles, rel: nightlies, rel: New in ..., slices, backcompat
