### ISSUE TITLE
Global NPC definitions not reloaded while using Test Game

### ISSUE THREAD

**Issue by meredosia** [ohrrpgce/ohrrpgce#1216] opened 2021-09-22 23:04 UTC
When resetting game, global npcs are invisible when repopulating the map.

**Comment by bob-the-hamster** [comment] 2021-09-23 01:14
Thank you for the bug report, @meredosia 

Can you please provide more information to help us try to reproduce this bug?

What do you mean by "resetting"? Saving and loading while playing a game? Exiting and re-opening the map editor? Step by step instructions to reproduce the bug are needed.

Screenshots might be helpful, if it is difficult to describe

**Comment by rversteegen** [comment] 2021-09-23 01:37
I did some simple tests but wasn't able to reproduce that.
Also, this in the hróðvitnir release, right?

**Comment by meredosia** [comment] 2021-09-23 06:45
sorry I was not more specific... I'm not sure how to explain. I use tags to
remove npcs from the map. then, when I start a new game, the removed npcs
are there (as they should be), but now invisible. this doesn't happen when
I close the game program and run a new test.

**Comment by rversteegen** [comment] 2021-09-25 07:10
OK, I've managed to reproduce this, but I think you're mistaken about what's going on. The problem is that while using Test Game any changes to Global NPC definitions made in Custom don't get reloaded by Game, so there are lots of different strange things that happen.

E.g. I created a one-time usable global NPC with a tag condition, then ran Test Game and used the NPC, then changed its tag condition so it should reappear, but it didn't. It wasn't invisible, but it did still show in NPC Debug mode (press F6). By moving my mouse over it in NPC debug mode I saw its tag condition was wrong.

Another variant on this bug is that while using Test Game, creating a new global NPC definition and then placing it on the map doesn't work. (In fact, you get a Fatal Bug error when mouse-overing it in NPC debug mode). 

I noticed another bug, which is that global NPCs don't get unique onetime-usable tags, as Custom doesn't check which tags are in use by global NPCs.

Finally, I notice that when I place a new NPC in the map editor while Testing Game and hit Ctrl-S, some NPCs on the map in Game reset to their initial position but not others, which seems buggy.

I had a list of global NPC bugs but never got around to going through that list before the hróðvitnir release; James had fixed a whole lot of bugs so my list was obsolete.

**Comment by meredosia** [comment] 2021-09-25 18:14
thanks. I've managed to work around some of those issues I had. Another
issue I've had with the new release is with directional walls. If I make a
tile impassable from the north, that bit of wall data carries on to the
north tile, so it becomes also impassable from both directions.

**Comment by bob-the-hamster** [comment] 2021-09-26 01:32
I spun off the bug about one-time-use tags not being handled correctly for global NPCs into a new issue #1219

@meredosia please file separate issues for separate bugs (And when you post an issue for the one about directional wals, please make sure to include a screenshot of the map editor in passability mode. It will make the bug easier to understand)

**Comment by rversteegen** [comment] 2021-09-26 05:10
(I can't reproduce any problem with one-way walls, but I don't know whether the complaint is about the map editor or in-game behaviour)

**Comment by rversteegen** [comment] 2021-09-30 22:46
This bug and all other known global NPC bugs are now fixed (in tonight's nightly builds) - there were quite a few! Thanks for the report. Let us know if you come across any more, or think that your one-way walls problem is a bug.

**Closed as completed by rversteegen** 2021-09-30 22:46 UTC
Labels: bug, Test Game, rel: New in ..., npcs, rel: hrodvitnir
